---
- name: "Enable Remi repo"
  yum:
    name: "{{ remi_repo_rpm_url }}"
    state: present

- name: "Uninstall problematic php70 packages"
  with_items:
    - "php70-php"
  yum:
    name: "{{ item }}"
    state: absent

- name: "Install php70 packages"
  with_items:
    - "php70"
    - "php70-build"
    - "php70-php-devel"
    - "php70-php-fpm"
    - "php70-php-mysqlnd"
    - "php70-php-pgsql"
  yum:
    name: "{{ item }}"
    state: present

- name: "Install httpd packages"
  with_items:
    - "httpd"
  yum:
    name: "{{ item }}"
    state: present
  when: require_httpd_package

- name: "Add missing httpd configuration file"
  copy:
    dest: "{{ httpd_php_conf_dest }}"
    src: "httpd-php.conf"
    owner: "{{ httpd_php_conf_owner }}"
    group: "{{ httpd_php_conf_group }}"
    mode: "{{ httpd_php_conf_mode }}"
    seuser: "{{ httpd_php_conf_seuser | default(omit) }}"
    serole: "{{ httpd_php_conf_serole | default(omit) }}"
    setype: "{{ httpd_php_conf_setype | default(omit) }}"
    selevel: "{{ httpd_php_conf_selevel | default(omit) }}"
  when: httpd_php_conf_copy

- name: "Enable php-fpm service"
  service:
    name: "php70-php-fpm"
    state: "{{ php_fpm_service_state }}"
    enabled: "{{ php_fpm_service_enabled }}"
